"""added user info table

Revision ID: 1de3dbbcae84
Revises: d961b20fec5d
Create Date: 2019-12-29 16:54:46.249805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de3dbbcae84'
down_revision = 'd961b20fec5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('registered_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registered_member_id'], ['user_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
